FROM php:8.2-fpm

# Установка зависимостей (при необходимости)
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    && docker-php-ext-install pdo pdo_mysql

# Установка PHP-расширений
RUN docker-php-ext-install pdo pdo_mysql

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Установка рабочего каталога
WORKDIR /var/www/html

# Копирование приложения в контейнер
COPY . .

# Копирование файла .env и выполнение команды для генерации ключа приложения
RUN cp .env.example .env && php artisan key:generate

# Разрешение на запись в определённые папки
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Создание ключа приложения, Запус миграций и Запуск Laravel сервера
CMD php artisan key:generate && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000
